JEANPHILIPPE2530/Matchable899

app/controllers/chatrooms_controller.rb, app/controllers/companies_controller.rb, app/controllers/developers_controller.rb, app/controllers/matches_controller.rb, app/controllers/messages_controller.rb, app/controllers/offers_controller.rb, app/controllers/user_controller.rb, app/models/company.rb, app/models/developer.rb, app/models/offer.rb, db/migrate/20220607073839_create_developers.rb, db/migrate/20220607074259_create_companies.rb, db/migrate/20220607074706_create_offers.rb, db/migrate/20220607075051_create_matches.rb, db/migrate/20220607075337_create_chatrooms.rb, db/migrate/20220607075639_create_messages.rb, db/migrate/20220607075909_create_skills.rb, db/migrate/20220607080114_create_offer_skills.rb, db/migrate/20220607080251_create_developer_skills.rb, db/schema.rb, test/controllers/chatrooms_controller_test.rb, test/controllers/companies_controller_test.rb, test/controllers/developers_controller_test.rb, test/controllers/matches_controller_test.rb, test/controllers/messages_controller_test.rb, test/controllers/offers_controller_test.rb, test/controllers/user_controller_test.rb, test/models/company_test.rb, test/models/developer_test.rb, test/models/offer_test.rb
Created models and controllers. Migrations.
=> Created models and controllers

config/routes.rb
Updated the routes. Validated by Dushyant.
=> Updated the routes

Gemfile.lock, app/views/layouts/application.html.erb
added links to fontawesome, google poppins, boxicons
=> added links to fonts

app/assets/stylesheets/pages/_forminput.scss, app/assets/stylesheets/pages/_index.scss, app/views/devise/registrations/new.html.erb, app/views/pages/home.html.erb, app/views/shared/_menu.html.erb
created some partials and started styling the form
=> front partials

app/views/shared/_menu.html.erb
Just pushing previously unsaved work.
=> Unsaved work

app/views/companies/new.html.erb, app/views/developers/new.html.erb, app/views/pages/_choice.html.erb, app/views/pages/home.html.erb, db/migrate/20220608065343_add_role_to_user.rb, db/schema.rb
Added "role" column to "Users" table. Do rails db:migrate.
=> Choice between continuing as developer or company

app/controllers/companies_controller.rb, app/views/companies/new.html.erb, app/views/developers/new.html.erb, app/views/pages/_choice.html.erb, app/views/pages/_welcome.html.erb, app/views/pages/home.html.erb, app/views/shared/_menu.html.erb
Worked on choices when visiting and signing up
=> Worked on choices when visiting and signing up

app/assets/stylesheets/application.scss, app/assets/stylesheets/profile/__developer_profile.scss, app/assets/stylesheets/profile/_index.scss, app/javascript/controllers/upload_resume.js, app/views/forms/_newdeveloper.html.erb
created developer profile form
=> created developer profile form

app/views/developers/new.html.erb, app/views/forms/_newdeveloper.html.erb
=> simple form

db/migrate/20220608115513_delete_offer_skill_table.rb, db/migrate/20220608115653_delete_developer_skills.rb, db/migrate/20220608115737_delete_skill_table.rb, db/migrate/20220608115848_add_skills_to_developers.rb, db/migrate/20220608115921_add_skills_to_offers.rb, db/schema.rb
removed skills tables and included skills to offers and developers
=> removed skills tables and included skills to offers and developers

app/assets/stylesheets/profile/_developer_profile.scss, app/models/developer.rb, app/views/developers/new.html.erb, app/views/forms/_newdeveloper.html.erb
=> fix profile developer

app/assets/stylesheets/profile/_build_profile.scss, app/views/forms/_newdeveloper.html.erb
=> Profile New developer

app/controllers/companies_controller.rb, app/controllers/developers_controller.rb
user.role is now updated to either "company" or "developer" after choosing a path and creating a profile.
=> Updated user role

app/controllers/application_controller.rb, app/controllers/companies_controller.rb, app/controllers/users_controller.rb, app/javascript/packs/application.js, app/views/pages/_choice.html.erb, app/views/shared/company/_company_full.html.erb, app/views/users/show.html.erb
Fixed logout not working + set user, company, developer everywhere
=> Fixed logout not working + set user, company, developer everywhere

app/views/developers/index.html.erb, config/routes.rb
=> Search (views)

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_search_result.scss
=> search result

app/assets/stylesheets/pages/_welcome.scss
=> Edit sign in and sign up btn

app/assets/stylesheets/profile/_build_profile.scss, app/views/companies/index.html.erb, app/views/companies/show.html.erb
=> Add back btn

app/views/shared/_card_swipe.html.erb
=> front match of developer

app/assets/stylesheets/components/_buttons.scss, app/views/errors/internal_server_error.html.erb, app/views/errors/not_found.html.erb
=> edit 404 and 500 pages

app/views/layouts/application.html.erb
=> fix favicon logo

db/seeds.rb
completed seeds for presentation
=> completed seeds for presentation

db/seeds.rb
=> change developer profile
